#DATALOADER:
#  TRAIN_X:
#    BATCH_SIZE: 64
#  TRAIN_U:
#    SAME_AS_X: False
#    BATCH_SIZE: 448
#  TEST:
#    BATCH_SIZE: 500
#
#OPTIM:
#  NAME: "sgd"
#  LR: 0.05
#  STEPSIZE: [4000]
#  MAX_EPOCH: 4000
#  LR_SCHEDULER: "cosine"
#
#TRAIN:
#  COUNT_ITER: "train_u"
#  PRINT_FREQ: 10
#
#TRAINER:
#  FIXMATCH:
#    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: "sgd"
  LR: 0.02
  STEPSIZE: [100]
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"

TRAIN:
  COUNT_ITER: "train_x"
  PRINT_FREQ: 5

TRAINER:
  NAME: "TrainerX"